/*
 * Copyright © 2008, 2015 Pedro Agulló Soliveres.
 * 
 * This file is part of DirectJNgine.
 *
 * DirectJNgine is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License.
 *
 * Commercial use is permitted to the extent that the code/component(s)
 * do NOT become part of another Open Source or Commercially developed
 * licensed development library or toolkit without explicit permission.
 *
 * DirectJNgine is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with DirectJNgine.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * This software uses the ExtJs library (http://extjs.com), which is 
 * distributed under the GPL v3 license (see http://extjs.com/license).
 */

package com.softwarementors.extjs.djn.test;

import java.util.HashMap;
import java.util.Map;

import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import com.softwarementors.extjs.djn.config.annotations.DirectMethod;

public class DirectStoreTest {
  public static class DirectStoreResult {
    @edu.umd.cs.findbugs.annotations.SuppressWarnings(value="URF_UNREAD_FIELD",
      justification="This field is read only in the Javascript side of DJN")
    private int rowCount;

    @edu.umd.cs.findbugs.annotations.SuppressWarnings(value="URF_UNREAD_FIELD",
      justification="This field is read only in the Javascript side of DJN")
    private Output[] items;
    
    public DirectStoreResult( Output[] result, int totalRows ) {
      assert result != null;
      
      this.rowCount = totalRows;
      
      // We create and store a copy of result to please FindBugs: in reality, it is not needed in this code, because it is a test!
      this.items = copyArray(result);
    }

    private static Output[] copyArray(Output[] result) {
      Output[] newItems = new Output[result.length];
      for( int i = 0; i < newItems.length; i++) {
        newItems[i] = result[i];
      }
      return newItems;
    }
  }
  
  public static class Output {
    @edu.umd.cs.findbugs.annotations.SuppressWarnings(value="URF_UNREAD_FIELD",
      justification="This field is read only in the Javascript side of DJN")
    private long id;

    @edu.umd.cs.findbugs.annotations.SuppressWarnings(value="URF_UNREAD_FIELD",
      justification="This field is read only in the Javascript side of DJN")
    private String name;
    
    /* This is not private just to remove the "Needless instantiation of class that only supplies static methods"
     * warning generated by FindBugs when instantiating this class! 
     */
    /* package */ void methodToAvoidNeedlesInstantiationOfClassThatOnlySuppliesStaticMethodsWarningInFindBugs() { 
      // Do nothing
    }
  }

  @DirectMethod
  public Output[] djn_test_load(String extraParam) {
    if( !extraParam.equals("aValue")) {
      throw new DirectTestFailedException( "Did no receive expected values");
    }
    Output[] result = new Output[2];
    result[0] = new Output();
    result[0].id = 99;
    result[0].name = "name1";

    result[1] = new Output();
    result[1].id = 100;
    result[1].name = "name2";
    
    /*
    DirectStoreResult r = new DirectStoreResult( result, 2);
    return r;
    */
    return result;
  }
  
  @DirectMethod
  public DirectStoreResult djn_test_load2() {
    Output[] result = new Output[2];
    result[0] = new Output();
    result[0].id = 99;
    result[0].name = "name1";

    result[1] = new Output();
    result[1].id = 100;
    result[1].name = "name2";
    
    DirectStoreResult r = new DirectStoreResult( result, 347);
    return r;
  }
  
  @DirectMethod
  public DirectStoreResult djn_test_loadWithArguments( int argPassedInLoadCall, boolean argPassedInBeforeLoadEvent, String argFromExtraParams ) {
    if( argPassedInLoadCall != 34 || argPassedInBeforeLoadEvent || !argFromExtraParams.equals("arg3")) {
      throw new DirectTestFailedException( "Did no receive expected values");
    }
    
    Output[] result = new Output[2];
    result[0] = new Output();
    result[0].id = 99;
    result[0].name = "name1";

    result[1] = new Output();
    result[1].id = 100;
    result[1].name = "name2";
    
    DirectStoreResult r = new DirectStoreResult( result, 347);
    return r;
  }
  
  public static class LoadArgs {
    public int argPassedInLoadCall;
    public boolean argPassedInBeforeLoadEvent;
    public String argFromExtraParams;  
  }
  
  @DirectMethod
  public DirectStoreResult djn_test_loadWithArgumentsUsingClass( LoadArgs param ) {
    return djn_test_loadWithArguments(param.argPassedInLoadCall, param.argPassedInBeforeLoadEvent, param.argFromExtraParams);
  }
  
  
  @DirectMethod
  public DirectStoreResult djn_test_loadWithArgumentsWithDirectJsonHandling( JsonArray arrayData ) {
    assert arrayData != null;

    JsonObject data = (JsonObject)arrayData.get(0);
    // Passing parameters to DirectStore via 'baseParams' is not supported in ExtJs 4, we must remove this check!
    // String argFromBaseParams = data.getAsJsonPrimitive("argFromBaseParams").getAsString();
    int argPassedInLoadCall = data.getAsJsonPrimitive("argPassedInLoadCall").getAsInt();
    boolean argPassedInBeforeLoadEvent = data.getAsJsonPrimitive("argPassedInBeforeLoadEvent").getAsBoolean();
    
    if( argPassedInLoadCall != 34 || argPassedInBeforeLoadEvent ) {
      throw new DirectTestFailedException( "Did no receive expected values");
    }
    
    Output[] result = new Output[2];
    result[0] = new Output();
    result[0].id = 99;
    result[0].name = "name1";

    result[1] = new Output();
    result[1].id = 100;
    result[1].name = "name2";
    
    DirectStoreResult r = new DirectStoreResult( result, 347);
    return r;
  }
  
  public static class Parameter {
    @edu.umd.cs.findbugs.annotations.SuppressWarnings(value="UWF_UNWRITTEN_FIELD",
        justification="This field is written only in the Javascript side of DJN")
    String param;

    @edu.umd.cs.findbugs.annotations.SuppressWarnings(value="UWF_UNWRITTEN_FIELD",
        justification="This field is written only in the Javascript side of DJN")
    String value;
    
    public static Map<String, String> toMap( Parameter[] parameters ) {
      assert parameters != null;
      
      Map<String, String> result = new HashMap<String,String>(parameters.length);
      for( Parameter parameter : parameters ) {
        result.put( parameter.param, parameter.value );
      }
      
      return result;
    }
  }
  
  
  @DirectMethod
  public DirectStoreResult test_simulatePassingDynamicParams( boolean param2, Parameter[] parameters) {
    assert parameters != null;
    
    Map<String, String> params = Parameter.toMap(parameters);
    String dyn1Value = params.get("dyn1");
    String dyn2Value = params.get("dyn2");
    if( !param2 ) {
      throw new DirectTestFailedException( "Expected param2 to be true");
    }
    if( !"55".equals(dyn1Value)) {
      throw new DirectTestFailedException( "Expected dynamic param 'dyn1' to be '55'");
    }
    if( !"dyn2Value".equals(dyn2Value)) {
      throw new DirectTestFailedException( "Expected dynamic param 'dyn2' to be 'dyn2Value'");
    }
    
    Output[] result = new Output[2];
    result[0] = new Output();
    result[0].id = 99;
    result[0].name = "name1";

    result[1] = new Output();
    result[1].id = 100;
    result[1].name = "name2";
    
    DirectStoreResult r = new DirectStoreResult( result, 347);
    return r;    
  }
}
